services:
  gateway:
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-qa}
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"

  frontend:
    image: openmrs/openmrs-reference-application-3-frontend:${TAG:-qa}
    restart: unless-stopped
    environment:
      - SPA_PATH=/openmrs/spa
      - API_URL=/openmrs
      - SPA_CONFIG_URLS=/openmrs/spa/config-core_demo.json
      - SPA_DEFAULT_LOCALE=
    depends_on:
      - backend

  backend:
    image: openmrs/openmrs-reference-application-3-backend:${TAG:-qa}
    restart: unless-stopped
    depends_on:
      - db
      - messagequeue
    environment:
      OMRS_DEV_DEBUG_PORT: "5005"
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OMRS_DB_USER}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OMRS_DB_PASSWORD}
      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_QUEUE_NAME: ${ACTIVEMQ_QUEUE_NAME}
      ACTIVEMQ_WEB_API_URL: ${ACTIVEMQ_WEB_API_URL}
      ACTIVEMQ_USERNAME: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      JAVA_TOOL_OPTIONS: >-
        -Djavax.net.ssl.trustStore=/opt/certs/client.ts
        -Djavax.net.ssl.trustStorePassword=${TRUSTSTORE_PASSWORD}
    volumes:
      - openmrs-data:/openmrs/data
      - ./saascommunication/omod/target/saascommunication-1.0.0-SNAPSHOT.omod:/openmrs/data/modules/saascommunication.omod
      - ./activemq/certs:/opt/certs:ro

  db:
    image: mariadb:10.11.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  messagequeue:
    image: apache/activemq-classic:6.1.6
    container_name: activemq-classic-omrs
    hostname: activemq-classic-omrs
    restart: unless-stopped
    environment:
      - ACTIVEMQ_WEB_USER=${ACTIVEMQ_USERNAME}
      - ACTIVEMQ_WEB_PASSWORD=${ACTIVEMQ_PASSWORD}
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61617:61617"
    volumes:
      - ./activemq/conf/activemq.xml:/opt/apache-activemq/conf/activemq.xml:ro
      - ./activemq/certs:/opt/apache-activemq/certs:ro

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  restapi:
    build:
      context: ./RestAPI
    restart: unless-stopped
    depends_on:
      - db
      - messagequeue
      - rabbitmq
      - fakecomworld
    environment:
      API_KEY: ${API_KEY}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      SWIFTSEND_URL: ${SWIFTSEND_URL}
      SWIFTSEND_API_KEY: ${SWIFTSEND_API_KEY}
      STUDENT_GROUP: ${STUDENT_GROUP}
      LEGACYLINK_URL: ${LEGACYLINK_URL}
      LEGACYLINK_AUTHORIZATION: ${LEGACYLINK_AUTHORIZATION}
      LEGACYLINK_SENDER: ${LEGACYLINK_SENDER}
      ASYNCFLOW_URL: ${ASYNCFLOW_URL}
      ASYNCFLOW_API_KEY: ${ASYNCFLOW_API_KEY}
      ASYNCFLOW_PRIORITY: ${ASYNCFLOW_PRIORITY}
      SECUREPOST_AUTH_URL: ${SECUREPOST_AUTH_URL}
      SECUREPOST_MESSAGE_URL: ${SECUREPOST_MESSAGE_URL}
      SECUREPOST_CLIENT_ID: ${SECUREPOST_CLIENT_ID}
      SECUREPOST_CLIENT_SECRET: ${SECUREPOST_CLIENT_SECRET}

      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_QUEUE_NAME: ${ACTIVEMQ_QUEUE_NAME}
      ACTIVEMQ_USERNAME: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      JAVA_TOOL_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Djavax.net.ssl.trustStore=/opt/certs/client.ts
        -Djavax.net.ssl.trustStorePassword=${TRUSTSTORE_PASSWORD}
    ports:
      - "8081:8081"
      - "5006:5005"
    volumes:
      - ./activemq/certs:/opt/certs:ro
  fakecomworld:
    image: ghcr.io/avansict/in2.4-fakecomworld:main
    container_name: fakecomworld
    restart: unless-stopped

    ports:
      - "1337:8080"
volumes:
  openmrs-data:
  db-data:
  rabbitmq-data:
