spring.application.name=RestAPI

server.port=8081

app.queue.name=openmrs.appointments

spring.activemq.broker-url=tcp://activemq-classic-omrs:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
