spring.application.name=RestAPI

server.port=8081

app.queue.name=${ACTIVEMQ_QUEUE_NAME}

security.api-key=${API_KEY}

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USERNAME}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

providers.swiftsend.url=${SWIFTSEND_URL}
providers.swiftsend.api-key=${SWIFTSEND_API_KEY}
providers.swiftsend.student-group=${STUDENT_GROUP}